# Generated by Django 2.1.5 on 2019-06-20 10:25

import app.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('round', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=25, unique=True)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('expired', models.DateTimeField(blank=True, default=app.models.now_plus_12_hours)),
                ('round', models.IntegerField(blank=True, default=1)),
                ('last_round', models.IntegerField(blank=True, default=1)),
                ('final_round', models.IntegerField(blank=True, default=0)),
                ('state', models.CharField(blank=True, choices=[('no_data', 'NoData'), ('waiting_for_players', 'WaitingForPlayers'), ('themes_all', 'ThemesAll'), ('themes_round', 'ThemesRound'), ('questions', 'Questions'), ('question_event', 'QuestionEvent'), ('question', 'Question'), ('question_end', 'QuestionEnd')], default='no_data', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('balance', models.IntegerField(blank=True, default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_theme', models.CharField(max_length=255)),
                ('text', models.TextField(null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('audio', models.CharField(max_length=255, null=True)),
                ('video', models.CharField(max_length=255, null=True)),
                ('value', models.IntegerField()),
                ('answer', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('is_question_end_required', models.BooleanField()),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('auction', 'Auction'), ('bagcat', 'BagCat')], max_length=25)),
                ('is_processed', models.BooleanField(blank=True, default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.Category')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='button_won_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.Question'),
        ),
        migrations.AddField(
            model_name='category',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app.Game'),
        ),
    ]
