# Generated by Django 2.1.5 on 2019-06-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190630_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='final_answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='player',
            name='final_bet',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
