# Generated by Django 2.1.5 on 2019-12-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190630_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='post_audio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='post_image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='post_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='post_video',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.CharField(blank=True, choices=[('waiting_for_players', 'WaitingForPlayers'), ('themes_all', 'ThemesAll'), ('themes_round', 'ThemesRound'), ('questions', 'Questions'), ('question_event', 'QuestionEvent'), ('question', 'Question'), ('question_end', 'QuestionEnd'), ('final_end', 'FinalEnd'), ('game_end', 'GameEnd')], default='waiting_for_players', max_length=25),
        ),
    ]
