# Generated by Django 2.1.5 on 2019-12-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191223_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_question_end_required',
        ),
    ]
